<#
.SYNOPSIS
    Win32 AppWorkload Log Analyzer - Parses Intune AppWorkload.log files and generates an HTML report.

.DESCRIPTION
    This tool parses Microsoft Intune's AppWorkload.log files (generated by the Intune Management Extension / SideCar agent)
    and produces a visual HTML report summarizing all Win32 app deployments on a device.

.PARAMETER LogFiles
    One or more AppWorkload.log file paths.

.PARAMETER LogFolder
    Folder path to auto-discover all AppWorkload*.log files.

.PARAMETER OutputPath
    Output path for the HTML report. Defaults to the same folder as the first log file.

.PARAMETER ShowInBrowser
    Auto-open the report in the default browser after generation.

.EXAMPLE
    .\Analyze-Win32AppWorkload.ps1 -LogFolder "C:\ProgramData\Microsoft\IntuneManagementExtension\Logs"
    .\Analyze-Win32AppWorkload.ps1 -LogFiles "C:\Logs\AppWorkload.log" -ShowInBrowser
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string[]]$LogFiles,

    [Parameter(Mandatory = $false)]
    [string]$LogFolder,

    [Parameter(Mandatory = $false)]
    [string]$OutputPath,

    [Parameter(Mandatory = $false)]
    [switch]$ShowInBrowser
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

# ============================================================
# Section 1: Value Mapping & Constants
# ============================================================

$IntentMap = @{
    0 = 'Available'
    3 = 'Required'
    4 = 'Uninstall'
}

$TargetTypeMap = @{
    1 = 'User'
    2 = 'Device'
}

$InstallContextMap = @{
    0 = 'User'
    1 = 'System'
}

$RunAsMap = @{
    1 = 'System'
    2 = 'User'
}

$DetectionTypeOuterMap = @{
    0 = 'Registry'
    1 = 'MSI Product Code'
    2 = 'File/Folder'
    3 = 'PowerShell Script'
}

$DetectionTypeInnerRegMap = @{
    1 = 'Exists'
    3 = 'String comparison'
    4 = 'Integer comparison'
    5 = 'Version comparison'
}

$DetectionTypeInnerFileMap = @{
    1 = 'Exists'
    4 = 'Version comparison'
}

$OperatorMap = @{
    0 = 'Exists'
    1 = 'Equal'
    2 = 'Not equal'
    3 = 'Greater than'
    4 = 'Greater than or equal'
    5 = 'Less than'
    6 = 'Less than or equal'
}

$ReturnCodeTypeMap = @{
    1 = 'Success'
    2 = 'Soft Reboot'
    3 = 'Hard Reboot'
    4 = 'Retry'
}

$ToastStateMap = @{
    0 = 'Hidden'
    2 = 'Show'
}

$DeviceRestartBehaviorMap = @{
    0 = 'Based on return code'
    1 = 'Allow restart'
    2 = 'Suppress restart'
    3 = 'Force restart'
}

# ============================================================
# Section 2: Helper Functions - Log Parsing
# ============================================================

function Parse-CMTraceLog {
    <#
    .SYNOPSIS
        Parse CMTrace/SCCM format log lines into structured objects.
    #>
    param(
        [Parameter(Mandatory)]
        [string[]]$LogContent
    )

    $pattern = '<!\[LOG\[(?<Message>.*?)\]LOG\]!><time="(?<Time>[\d:.]+)" date="(?<Date>[\d-]+)" component="(?<Component>\w*)" context="(?<Context>[^"]*)" type="(?<Type>\d)" thread="(?<Thread>\d+)" file="(?<File>[^"]*)">'

    $results = [System.Collections.Generic.List[PSCustomObject]]::new()

    foreach ($line in $LogContent) {
        if ($line -match $pattern) {
            $dateStr = $Matches['Date']
            $timeStr = $Matches['Time']
            $dt = $null
            try {
                $dt = [DateTime]::ParseExact("$dateStr $timeStr", "M-d-yyyy HH:mm:ss.fffffff", $null)
            }
            catch {
                try {
                    $dt = [DateTime]::ParseExact("$dateStr $timeStr", "M-d-yyyy HH:mm:ss.fff", $null)
                }
                catch {
                    try { $dt = [DateTime]::Parse("$dateStr $timeStr") } catch { $dt = [DateTime]::MinValue }
                }
            }

            $results.Add([PSCustomObject]@{
                Message   = $Matches['Message']
                DateTime  = $dt
                Component = $Matches['Component']
                Type      = [int]$Matches['Type']
                Thread    = $Matches['Thread']
                File      = $Matches['File']
            })
        }
    }

    return $results
}

function Merge-LogFiles {
    <#
    .SYNOPSIS
        Merge multiple AppWorkload log files chronologically.
    #>
    param(
        [Parameter(Mandatory)]
        [string[]]$FilePaths
    )

    # Separate current file from rotated files
    # Handles both standard names (AppWorkload.log) and prefixed names (DeviceName_AppWorkload.log)
    $currentFile = $null
    $rotatedFiles = @()

    foreach ($fp in $FilePaths) {
        $name = [System.IO.Path]::GetFileNameWithoutExtension($fp)
        # Current file: ends with 'AppWorkload' (no timestamp suffix)
        if ($name -match '^(.*_)?AppWorkload$') {
            $currentFile = $fp
        }
        else {
            $rotatedFiles += $fp
        }
    }

    # Sort rotated files by timestamp suffix (oldest first)
    $rotatedFiles = $rotatedFiles | Sort-Object {
        $n = [System.IO.Path]::GetFileNameWithoutExtension($_)
        if ($n -match 'AppWorkload-(\d{8}-\d{6})') { $Matches[1] } else { $n }
    }

    # Build ordered file list: rotated (oldest->newest), then current
    $orderedFiles = @()
    $orderedFiles += $rotatedFiles
    if ($currentFile) { $orderedFiles += $currentFile }

    # Read and merge all content
    $allLines = [System.Collections.Generic.List[string]]::new()
    foreach ($f in $orderedFiles) {
        Write-Host "  Reading: $(Split-Path $f -Leaf)" -ForegroundColor Cyan
        $content = Get-Content -Path $f -Raw -ErrorAction SilentlyContinue
        if ($content) {
            $lines = $content -split "`r?`n"
            foreach ($l in $lines) {
                if ($l.Trim()) { $allLines.Add($l) }
            }
        }
    }

    return $allLines.ToArray()
}

# ============================================================
# Section 3: Helper Functions - Policy & Detection Parsing
# ============================================================

function Parse-PolicyJSON {
    <#
    .SYNOPSIS
        Extract the latest "Get policies" JSON and build an app inventory.
    #>
    param(
        [Parameter(Mandatory)]
        [PSCustomObject[]]$LogEntries
    )

    $policyEntries = @($LogEntries | Where-Object { $_.Message -match '^Get policies = \[' })

    if ($policyEntries.Count -eq 0) {
        Write-Warning "No 'Get policies' line found in the log."
        return @{}
    }

    # Take the LAST occurrence that has actual app data (non-empty JSON array)
    # Some check-in sessions may return "Get policies = []" (empty)
    $lastPolicy = $null
    $apps = $null
    for ($i = $policyEntries.Count - 1; $i -ge 0; $i--) {
        $candidate = $policyEntries[$i]
        $candidateJson = $candidate.Message -replace '^Get policies = ', ''
        if ($candidateJson -and $candidateJson -ne '[]') {
            try {
                $parsedApps = $candidateJson | ConvertFrom-Json
                if ($parsedApps -and @($parsedApps).Count -gt 0) {
                    $lastPolicy = $candidate
                    $apps = $parsedApps
                    break
                }
            }
            catch { continue }
        }
    }

    if (-not $apps) {
        Write-Warning "All 'Get policies' entries contain empty app lists."
        return @{}
    }

    Write-Host "  Using policy entry with $(@($apps).Count) app(s) from $($lastPolicy.DateTime)" -ForegroundColor Gray

    $inventory = [ordered]@{}
    foreach ($app in $apps) {
        $appId = $app.Id
        $inventory[$appId] = [PSCustomObject]@{
            AppId              = $appId
            Name               = $app.Name
            Intent             = $app.Intent
            IntentName         = if ($IntentMap.ContainsKey([int]$app.Intent)) { $IntentMap[[int]$app.Intent] } else { "Unknown($($app.Intent))" }
            TargetType         = $app.TargetType
            TargetTypeName     = if ($TargetTypeMap.ContainsKey([int]$app.TargetType)) { $TargetTypeMap[[int]$app.TargetType] } else { "Unknown($($app.TargetType))" }
            InstallContext     = $app.InstallContext
            InstallContextName = if ($InstallContextMap.ContainsKey([int]$app.InstallContext)) { $InstallContextMap[[int]$app.InstallContext] } else { "Unknown($($app.InstallContext))" }
            InstallCommandLine = $app.InstallCommandLine
            UninstallCommandLine = $app.UninstallCommandLine
            DetectionRules     = Parse-DetectionRules -DetectionRuleJson $app.DetectionRule
            InstallBehavior    = Parse-InstallEx -InstallExJson $app.InstallEx
            ReturnCodes        = Parse-ReturnCodes -ReturnCodesJson $app.ReturnCodes
            ToastState         = if ($ToastStateMap.ContainsKey([int]$app.ToastState)) { $ToastStateMap[[int]$app.ToastState] } else { "$($app.ToastState)" }
            ReevaluationInterval = $app.ReevaluationInterval
            DOPriority         = $app.DOPriority
            Dependencies       = $app.FlatDependencies
            Version            = $app.Version
            # Event tracking - populated later
            DetectionState     = $null
            DetectionStatus    = $null
            ApplicabilityState = $null
            DownloadStatus     = $null
            DownloadTimestamp  = $null
            InstallStartTime   = $null
            InstallExitCode    = $null
            InstallResult      = $null
            InstallCompleteTime = $null
            PostInstallDetection = $null
            EnforcementStates  = @()
            LatestEnforcementState = $null
            EspPhase           = $null
            Errors             = @()
            EventTimeline      = @()
            CheckinSession     = $null
        }
    }

    return $inventory
}

function Parse-DetectionRules {
    param([string]$DetectionRuleJson)

    if (-not $DetectionRuleJson) { return @() }

    $rules = @()
    try {
        $ruleArray = $DetectionRuleJson | ConvertFrom-Json
    }
    catch { return @("Failed to parse detection rules") }

    foreach ($rule in $ruleArray) {
        $outerType = [int]$rule.DetectionType
        $outerTypeName = if ($DetectionTypeOuterMap.ContainsKey($outerType)) { $DetectionTypeOuterMap[$outerType] } else { "Type $outerType" }

        if (-not $rule.DetectionText) {
            $rules += "$outerTypeName (no details)"
            continue
        }

        try {
            $inner = $rule.DetectionText | ConvertFrom-Json
        }
        catch {
            $rules += "$outerTypeName (parse error)"
            continue
        }

        switch ($outerType) {
            0 {
                # Registry
                $innerType = if ($DetectionTypeInnerRegMap.ContainsKey([int]$inner.DetectionType)) { $DetectionTypeInnerRegMap[[int]$inner.DetectionType] } else { "Type $($inner.DetectionType)" }
                $op = if ($OperatorMap.ContainsKey([int]$inner.Operator)) { $OperatorMap[[int]$inner.Operator] } else { "Op $($inner.Operator)" }
                $ruleDesc = "Registry: $($inner.Path)\$($inner.KeyName) | $innerType | $op"
                if ($inner.DetectionValue) { $ruleDesc += " | Expected: $($inner.DetectionValue)" }
                $rules += $ruleDesc
            }
            2 {
                # File/Folder
                $innerType = if ($DetectionTypeInnerFileMap.ContainsKey([int]$inner.DetectionType)) { $DetectionTypeInnerFileMap[[int]$inner.DetectionType] } else { "Type $($inner.DetectionType)" }
                $op = if ($OperatorMap.ContainsKey([int]$inner.Operator)) { $OperatorMap[[int]$inner.Operator] } else { "Op $($inner.Operator)" }
                $ruleDesc = "File: $($inner.Path)\$($inner.FileOrFolderName) | $innerType | $op"
                if ($inner.DetectionValue) { $ruleDesc += " | Expected: $($inner.DetectionValue)" }
                $rules += $ruleDesc
            }
            3 {
                # Script
                $rules += "PowerShell Script Detection (EnforceSignatureCheck: $($inner.EnforceSignatureCheck), RunAs32Bit: $($inner.RunAs32Bit))"
            }
            1 {
                # MSI
                $rules += "MSI Product Code: $($inner.ProductCode)"
            }
            default {
                $rules += "$outerTypeName (details available)"
            }
        }
    }

    return $rules
}

function Parse-InstallEx {
    param([string]$InstallExJson)

    if (-not $InstallExJson) { return $null }

    try {
        $obj = $InstallExJson | ConvertFrom-Json
        return [PSCustomObject]@{
            RunAs                   = if ($RunAsMap.ContainsKey([int]$obj.RunAs)) { $RunAsMap[[int]$obj.RunAs] } else { "$($obj.RunAs)" }
            RequiresLogon           = $obj.RequiresLogon
            MaxRetries              = $obj.MaxRetries
            RetryIntervalInMinutes  = $obj.RetryIntervalInMinutes
            MaxRunTimeInMinutes     = $obj.MaxRunTimeInMinutes
            DeviceRestartBehavior   = if ($DeviceRestartBehaviorMap.ContainsKey([int]$obj.DeviceRestartBehavior)) { $DeviceRestartBehaviorMap[[int]$obj.DeviceRestartBehavior] } else { "Unknown($($obj.DeviceRestartBehavior))" }
            InstallProgramVisibility = $obj.InstallProgramVisibility
        }
    }
    catch { return $null }
}

function Parse-ReturnCodes {
    param([string]$ReturnCodesJson)

    if (-not $ReturnCodesJson) { return @() }

    try {
        $codes = $ReturnCodesJson | ConvertFrom-Json
        return $codes | ForEach-Object {
            [PSCustomObject]@{
                ReturnCode = $_.ReturnCode
                TypeName   = if ($ReturnCodeTypeMap.ContainsKey([int]$_.Type)) { $ReturnCodeTypeMap[[int]$_.Type] } else { "Unknown($($_.Type))" }
            }
        }
    }
    catch { return @() }
}

# ============================================================
# Section 4: Per-App Event Extraction
# ============================================================

function Get-AppEvents {
    <#
    .SYNOPSIS
        For each app, search the log for all relevant events and populate event data.
    #>
    param(
        [Parameter(Mandatory)]
        [PSCustomObject[]]$LogEntries,

        [Parameter(Mandatory)]
        [hashtable]$AppInventory,

        [Parameter(Mandatory)]
        [PSCustomObject[]]$EspPhaseEvents
    )

    foreach ($appId in $AppInventory.Keys) {
        $app = $AppInventory[$appId]
        $timeline = [System.Collections.Generic.List[PSCustomObject]]::new()
        $errors = [System.Collections.Generic.List[PSCustomObject]]::new()

        # Filter log entries mentioning this AppId
        $appEntries = $LogEntries | Where-Object { $_.Message -match [regex]::Escape($appId) }

        # --- Detection State ---
        $detectionEntries = $appEntries | Where-Object {
            $_.Message -match '\[DetectionActionHandler\].*Detection for policy with id:.*resulted in action status:'
        }
        if ($detectionEntries) {
            $lastDetection = $detectionEntries | Select-Object -Last 1
            if ($lastDetection.Message -match 'action status:\s*(\w+)\s*and detection state:\s*(\w+)') {
                $app.DetectionStatus = $Matches[1]
                $app.DetectionState = $Matches[2]
            }
            foreach ($d in $detectionEntries) {
                $timeline.Add([PSCustomObject]@{ Time = $d.DateTime; Event = 'Detection'; Detail = $d.Message; Type = $d.Type })
            }
        }

        # --- Applicability ---
        $applicabilityEntries = $appEntries | Where-Object {
            $_.Message -match '\[ApplicabilityActionHandler\].*Applicability check for policy with id:.*resulted in'
        }
        if ($applicabilityEntries) {
            $lastApplic = $applicabilityEntries | Select-Object -Last 1
            if ($lastApplic.Message -match 'applicability state:\s*(\w+)') {
                $app.ApplicabilityState = $Matches[1]
            }
            foreach ($a in $applicabilityEntries) {
                $timeline.Add([PSCustomObject]@{ Time = $a.DateTime; Event = 'Applicability'; Detail = $a.Message; Type = $a.Type })
            }
        }

        # --- Download ---
        $downloadStartEntries = $appEntries | Where-Object {
            $_.Message -match '\[DownloadActionHandler\] Handler invoked for policy with id:'
        }
        if ($downloadStartEntries) {
            $lastDlStart = $downloadStartEntries | Select-Object -Last 1
            $app.DownloadTimestamp = $lastDlStart.DateTime
            $timeline.Add([PSCustomObject]@{ Time = $lastDlStart.DateTime; Event = 'Download Start'; Detail = $lastDlStart.Message; Type = $lastDlStart.Type })
        }

        $downloadCompleteEntries = $appEntries | Where-Object {
            $_.Message -match '\[ContentManagerV2\].*Completed.*content download.*result status:'
        }
        if ($downloadCompleteEntries) {
            $lastDlComplete = $downloadCompleteEntries | Select-Object -Last 1
            if ($lastDlComplete.Message -match 'result status:\s*(\w+)') {
                $app.DownloadStatus = $Matches[1]
            }
            $timeline.Add([PSCustomObject]@{ Time = $lastDlComplete.DateTime; Event = 'Download Complete'; Detail = $lastDlComplete.Message; Type = $lastDlComplete.Type })
        }

        # --- Install Start ---
        $installStartEntries = $appEntries | Where-Object {
            $_.Message -match '\[ExecutionActionHandler\] Handler invoked with execution type:\s*Install\s*for policy with id:'
        }
        if ($installStartEntries) {
            $lastInstStart = $installStartEntries | Select-Object -Last 1
            $app.InstallStartTime = $lastInstStart.DateTime
            $timeline.Add([PSCustomObject]@{ Time = $lastInstStart.DateTime; Event = 'Install Start'; Detail = $lastInstStart.Message; Type = $lastInstStart.Type })
        }

        # --- Install Exit Code & Result ---
        # Find lpExitCode entries after the install start for this app
        if ($app.InstallStartTime) {
            $postInstallEntries = $LogEntries | Where-Object {
                $_.DateTime -ge $app.InstallStartTime -and $_.DateTime -le $app.InstallStartTime.AddMinutes(120)
            }

            $exitCodeEntry = $postInstallEntries | Where-Object { $_.Message -match '^lpExitCode\s+(-?\d+)$' } | Select-Object -First 1
            if ($exitCodeEntry) {
                if ($exitCodeEntry.Message -match 'lpExitCode\s+(-?\d+)') {
                    $app.InstallExitCode = $Matches[1]
                }
                $timeline.Add([PSCustomObject]@{ Time = $exitCodeEntry.DateTime; Event = 'Exit Code'; Detail = $exitCodeEntry.Message; Type = $exitCodeEntry.Type })
            }

            $resultEntry = $postInstallEntries | Where-Object { $_.Message -match 'lpExitCode is defined as\s+(\w+)' } | Select-Object -First 1
            if ($resultEntry) {
                if ($resultEntry.Message -match 'lpExitCode is defined as\s+(\w+)') {
                    $app.InstallResult = $Matches[1]
                }
                $timeline.Add([PSCustomObject]@{ Time = $resultEntry.DateTime; Event = 'Install Result'; Detail = $resultEntry.Message; Type = $resultEntry.Type })
            }
        }

        # --- Install Complete ---
        $installCompleteEntries = $appEntries | Where-Object {
            $_.Message -match '\[ExecutionActionHandler\] Handler completed with action status:'
        }
        if ($installCompleteEntries) {
            $lastInstComplete = $installCompleteEntries | Select-Object -Last 1
            $app.InstallCompleteTime = $lastInstComplete.DateTime
            $timeline.Add([PSCustomObject]@{ Time = $lastInstComplete.DateTime; Event = 'Install Complete'; Detail = $lastInstComplete.Message; Type = $lastInstComplete.Type })
        }

        # --- Post-Install Detection ---
        $postDetEntries = $appEntries | Where-Object {
            $_.Message -match '\[DetectionActionHandler\].*Policy with id:.*is expected to have enforcement state:\s*Detected'
        }
        if ($postDetEntries) {
            $timeline.Add([PSCustomObject]@{ Time = ($postDetEntries | Select-Object -Last 1).DateTime; Event = 'Post-Install Detection Expected'; Detail = ($postDetEntries | Select-Object -Last 1).Message; Type = 1 })
        }

        # --- Enforcement State Tracking ---
        $enforcementEntries = $appEntries | Where-Object {
            $_.Message -match '\[ReportingManager\].*Download state for app with id:.*EnforcementState'
        }
        $enfStates = @()
        foreach ($e in $enforcementEntries) {
            if ($e.Message -match '"NewValue":"?([^",}]+)"?') {
                $enfStates += [PSCustomObject]@{ Time = $e.DateTime; State = $Matches[1] }
                $timeline.Add([PSCustomObject]@{ Time = $e.DateTime; Event = 'Enforcement State'; Detail = "EnforcementState -> $($Matches[1])"; Type = $e.Type })
            }
        }
        $app.EnforcementStates = $enfStates
        if ($enfStates.Count -gt 0) {
            $app.LatestEnforcementState = ($enfStates | Select-Object -Last 1).State
        }

        # --- Errors ---
        $errorEntries = $appEntries | Where-Object { $_.Type -eq 3 }
        foreach ($err in $errorEntries) {
            $errors.Add([PSCustomObject]@{
                Time    = $err.DateTime
                Message = $err.Message
                AppId   = $appId
                AppName = $app.Name
            })
            $timeline.Add([PSCustomObject]@{ Time = $err.DateTime; Event = 'Error'; Detail = $err.Message; Type = 3 })
        }

        # --- ESP Phase ---
        if ($app.InstallStartTime -and $EspPhaseEvents.Count -gt 0) {
            $app.EspPhase = Get-EspPhaseAtTime -EspPhaseEvents $EspPhaseEvents -TargetTime $app.InstallStartTime
        }
        elseif ($EspPhaseEvents.Count -gt 0) {
            $app.EspPhase = ($EspPhaseEvents | Select-Object -Last 1).Phase
        }

        # Sort timeline
        $app.EventTimeline = $timeline | Sort-Object Time
        $app.Errors = $errors
    }
}

function Get-EspPhaseAtTime {
    param(
        [PSCustomObject[]]$EspPhaseEvents,
        [DateTime]$TargetTime
    )

    $before = $EspPhaseEvents | Where-Object { $_.Time -le $TargetTime } | Select-Object -Last 1
    if ($before) { return $before.Phase }
    return 'Unknown'
}

function Get-EspPhaseEvents {
    param([PSCustomObject[]]$LogEntries)

    $espEvents = [System.Collections.Generic.List[PSCustomObject]]::new()
    foreach ($entry in $LogEntries) {
        if ($entry.Message -match 'The EspPhase:\s*(\w+)' -or $entry.Message -match 'EspPhase:\s*(\w+)') {
            $espEvents.Add([PSCustomObject]@{
                Time  = $entry.DateTime
                Phase = $Matches[1]
            })
        }
    }
    return $espEvents.ToArray()
}

function Get-CheckinSessions {
    param([PSCustomObject[]]$LogEntries)

    $sessions = [System.Collections.Generic.List[PSCustomObject]]::new()
    $sessionStart = $null

    foreach ($entry in $LogEntries) {
        if ($entry.Message -match '\[Win32AppAsync\] Starting app check in' -or
            $entry.Message -match '----- application poller starts\. -----') {
            $sessionStart = $entry.DateTime
        }

        if ($sessionStart -and $entry.Message -match 'Got (\d+) active user sessions') {
            $sessions.Add([PSCustomObject]@{
                StartTime    = $sessionStart
                UserSessions = [int]$Matches[1]
            })
        }
    }
    return $sessions.ToArray()
}

function Get-AllErrors {
    param(
        [PSCustomObject[]]$LogEntries,
        [hashtable]$AppInventory
    )

    $appIds = @($AppInventory.Keys)
    $generalErrors = [System.Collections.Generic.List[PSCustomObject]]::new()

    foreach ($entry in ($LogEntries | Where-Object { $_.Type -eq 3 })) {
        # Check if this error mentions any known AppId
        $isAppSpecific = $false
        foreach ($id in $appIds) {
            if ($entry.Message -match [regex]::Escape($id)) {
                $isAppSpecific = $true
                break
            }
        }
        if (-not $isAppSpecific) {
            $generalErrors.Add([PSCustomObject]@{
                Time    = $entry.DateTime
                Message = $entry.Message
            })
        }
    }
    return $generalErrors.ToArray()
}

# ============================================================
# Section 5: HTML Report Generation
# ============================================================

function Get-ReportCss {
    return @'
:root {
    --primary: #0078D4;
    --success: #107C10;
    --error: #D13438;
    --warning: #FFB900;
    --info: #00B7C3;
    --bg-primary: #FFFFFF;
    --bg-secondary: #F3F2F1;
    --bg-card: #FFFFFF;
    --text-primary: #323130;
    --text-secondary: #605E5C;
    --border: #EDEBE9;
}

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
    color: var(--text-primary);
    background: var(--bg-secondary);
    line-height: 1.5;
}

.container {
    max-width: 1400px;
    margin: 0 auto;
    padding: 24px;
}

.report-header {
    background: linear-gradient(135deg, var(--primary), #106EBE);
    color: white;
    padding: 32px;
    border-radius: 8px;
    margin-bottom: 24px;
}

.report-header h1 { font-size: 24px; font-weight: 600; margin-bottom: 8px; }
.report-header .subtitle { font-size: 14px; opacity: 0.9; }
.report-header .meta { font-size: 12px; opacity: 0.8; margin-top: 12px; }
.report-header .meta span { margin-right: 20px; }

.dashboard {
    display: flex;
    flex-wrap: wrap;
    gap: 16px;
    margin-bottom: 24px;
}

.card {
    background: var(--bg-card);
    border-radius: 8px;
    padding: 20px;
    flex: 1;
    min-width: 160px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    border-top: 4px solid var(--primary);
    text-align: center;
}

.card .card-value { font-size: 32px; font-weight: 700; }
.card .card-label { font-size: 12px; text-transform: uppercase; color: var(--text-secondary); margin-top: 4px; letter-spacing: 0.5px; }
.card.success { border-top-color: var(--success); }
.card.success .card-value { color: var(--success); }
.card.error { border-top-color: var(--error); }
.card.error .card-value { color: var(--error); }
.card.warning { border-top-color: var(--warning); }
.card.warning .card-value { color: var(--warning); }
.card.info { border-top-color: var(--info); }
.card.info .card-value { color: var(--info); }
.card.neutral { border-top-color: #8A8886; }
.card.neutral .card-value { color: #8A8886; }
.card.purple { border-top-color: #8764B8; }
.card.purple .card-value { color: #8764B8; font-size: 18px; }

.controls {
    background: var(--bg-card);
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 16px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    align-items: center;
}

.controls input[type="text"] {
    padding: 8px 12px;
    border: 1px solid var(--border);
    border-radius: 4px;
    font-size: 13px;
    min-width: 250px;
}

.controls select {
    padding: 8px 12px;
    border: 1px solid var(--border);
    border-radius: 4px;
    font-size: 13px;
    background: white;
}

.controls button, .btn {
    padding: 8px 16px;
    border: 1px solid var(--border);
    border-radius: 4px;
    font-size: 13px;
    background: white;
    cursor: pointer;
    transition: background 0.2s;
}

.controls button:hover, .btn:hover {
    background: var(--bg-secondary);
}

.btn-primary {
    background: var(--primary) !important;
    color: white !important;
    border-color: var(--primary) !important;
}

.btn-primary:hover { opacity: 0.9; }

.section {
    background: var(--bg-card);
    border-radius: 8px;
    margin-bottom: 24px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    overflow: hidden;
}

.section-header {
    padding: 16px 20px;
    font-size: 18px;
    font-weight: 600;
    border-bottom: 1px solid var(--border);
    background: var(--bg-secondary);
    cursor: pointer;
    user-select: none;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.section-header .toggle { font-size: 14px; color: var(--text-secondary); }

.app-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
}

.app-table th {
    background: var(--bg-secondary);
    padding: 10px 12px;
    text-align: left;
    font-weight: 600;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: var(--text-secondary);
    border-bottom: 2px solid var(--border);
    cursor: pointer;
    white-space: nowrap;
    user-select: none;
}

.app-table th:hover { background: #E1DFDD; }
.app-table th .sort-icon { margin-left: 4px; font-size: 10px; }

.app-table td {
    padding: 10px 12px;
    border-bottom: 1px solid var(--border);
    vertical-align: middle;
}

.app-table tr:hover { background: #F5F5F5; }
.app-table tr.app-row { cursor: pointer; }

.badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 11px;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.3px;
}

.badge-required { background: #E8F0FE; color: var(--primary); }
.badge-available { background: #F3F2F1; color: #605E5C; }
.badge-uninstall { background: #FDE7E9; color: var(--error); }
.badge-user { background: #E8F5E9; color: #2E7D32; }
.badge-device { background: #E3F2FD; color: #1565C0; }
.badge-system { background: #FFF3E0; color: #E65100; }
.badge-detected { background: #E8F5E9; color: var(--success); }
.badge-notdetected { background: #FDE7E9; color: var(--error); }
.badge-success { background: #E8F5E9; color: var(--success); }
.badge-failed { background: #FDE7E9; color: var(--error); }
.badge-pending { background: #FFF8E1; color: #F57F17; }
.badge-noactivity { background: #F3F2F1; color: #8A8886; }

.status-icon { font-size: 18px; text-align: center; }

.detail-row { display: none; }
.detail-row.active { display: table-row; }
.detail-content {
    padding: 20px;
    background: #FAFAFA;
}

.detail-content h4 {
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 8px;
    margin-top: 16px;
    color: var(--primary);
}

.detail-content h4:first-child { margin-top: 0; }

.detail-content .code-block {
    background: #2D2D2D;
    color: #D4D4D4;
    padding: 12px;
    border-radius: 4px;
    font-family: 'Cascadia Code', 'Consolas', monospace;
    font-size: 12px;
    overflow-x: auto;
    margin-bottom: 8px;
    word-break: break-all;
}

.detail-content .info-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 8px;
    margin-bottom: 12px;
}

.detail-content .info-item {
    display: flex;
    gap: 8px;
}

.detail-content .info-item .label {
    font-weight: 600;
    color: var(--text-secondary);
    min-width: 120px;
    font-size: 12px;
}

.detail-content .info-item .value {
    font-size: 12px;
}

.timeline-list {
    list-style: none;
    position: relative;
    padding-left: 20px;
}

.timeline-list::before {
    content: '';
    position: absolute;
    left: 6px;
    top: 0;
    bottom: 0;
    width: 2px;
    background: var(--border);
}

.timeline-list li {
    position: relative;
    padding: 6px 0 6px 16px;
    font-size: 12px;
}

.timeline-list li::before {
    content: '';
    position: absolute;
    left: -16px;
    top: 12px;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: var(--primary);
    border: 2px solid white;
}

.timeline-list li.error-event::before { background: var(--error); }
.timeline-list li.success-event::before { background: var(--success); }
.timeline-list li.warning-event::before { background: var(--warning); }

.timeline-list .time {
    font-weight: 600;
    color: var(--text-secondary);
    margin-right: 8px;
    font-family: 'Cascadia Code', 'Consolas', monospace;
    font-size: 11px;
}

.timeline-list .event-type {
    display: inline-block;
    padding: 1px 6px;
    border-radius: 3px;
    font-size: 10px;
    font-weight: 600;
    text-transform: uppercase;
    margin-right: 6px;
    background: #E8F0FE;
    color: var(--primary);
}

.error-summary-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 12px;
}

.error-summary-table th {
    background: var(--bg-secondary);
    padding: 8px 12px;
    text-align: left;
    font-weight: 600;
    font-size: 11px;
    text-transform: uppercase;
    border-bottom: 2px solid var(--border);
}

.error-summary-table td {
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
    font-size: 12px;
}

.error-summary-table tr:hover { background: #FFF5F5; }
.error-msg { color: var(--error); word-break: break-word; }

.return-codes-table {
    width: auto;
    border-collapse: collapse;
    font-size: 12px;
    margin-bottom: 12px;
}

.return-codes-table th, .return-codes-table td {
    padding: 4px 12px;
    border: 1px solid var(--border);
    text-align: left;
}

.return-codes-table th { background: var(--bg-secondary); font-weight: 600; }

.detection-rules { margin-bottom: 12px; }
.detection-rules li {
    font-size: 12px;
    padding: 4px 0;
    font-family: 'Cascadia Code', 'Consolas', monospace;
}

@media (max-width: 1024px) {
    .container { padding: 12px; }
    .dashboard { flex-direction: column; }
    .card { min-width: 100%; }
    .app-table { display: block; overflow-x: auto; }
}
'@
}

function Get-ReportJavaScript {
    return @'
function filterApps() {
    const searchText = document.getElementById('searchBox').value.toLowerCase();
    const statusFilter = document.getElementById('statusFilter').value;
    const intentFilter = document.getElementById('intentFilter').value;
    const rows = document.querySelectorAll('.app-row');

    rows.forEach(row => {
        const name = row.getAttribute('data-name').toLowerCase();
        const status = row.getAttribute('data-status');
        const intent = row.getAttribute('data-intent');
        const detailRow = document.getElementById('detail-' + row.getAttribute('data-appid'));

        let show = true;
        if (searchText && !name.includes(searchText)) show = false;
        if (statusFilter && statusFilter !== 'all' && status !== statusFilter) show = false;
        if (intentFilter && intentFilter !== 'all' && intent !== intentFilter) show = false;

        row.style.display = show ? '' : 'none';
        if (detailRow) detailRow.style.display = 'none';
        if (detailRow) detailRow.classList.remove('active');
    });
}

function toggleDetail(appId) {
    const detailRow = document.getElementById('detail-' + appId);
    if (detailRow) {
        detailRow.classList.toggle('active');
        detailRow.style.display = detailRow.classList.contains('active') ? 'table-row' : 'none';
    }
}

function toggleAllDetails() {
    const detailRows = document.querySelectorAll('.detail-row');
    const anyHidden = Array.from(detailRows).some(r => !r.classList.contains('active'));

    detailRows.forEach(r => {
        if (anyHidden) {
            r.classList.add('active');
            r.style.display = 'table-row';
        } else {
            r.classList.remove('active');
            r.style.display = 'none';
        }
    });
}

let sortDirection = {};

function sortTable(colIndex) {
    const table = document.getElementById('appTable');
    const tbody = table.querySelector('tbody');
    const rows = Array.from(tbody.querySelectorAll('tr.app-row'));

    sortDirection[colIndex] = !sortDirection[colIndex];
    const dir = sortDirection[colIndex] ? 1 : -1;

    rows.sort((a, b) => {
        const aVal = a.cells[colIndex].textContent.trim().toLowerCase();
        const bVal = b.cells[colIndex].textContent.trim().toLowerCase();
        if (!isNaN(aVal) && !isNaN(bVal)) return (parseFloat(aVal) - parseFloat(bVal)) * dir;
        return aVal.localeCompare(bVal) * dir;
    });

    rows.forEach(row => {
        const detailRow = document.getElementById('detail-' + row.getAttribute('data-appid'));
        tbody.appendChild(row);
        if (detailRow) tbody.appendChild(detailRow);
    });

    // Update sort icons
    const headers = table.querySelectorAll('th');
    headers.forEach((h, i) => {
        const icon = h.querySelector('.sort-icon');
        if (icon) icon.textContent = i === colIndex ? (sortDirection[colIndex] ? ' ▲' : ' ▼') : '';
    });
}

function exportCSV() {
    const table = document.getElementById('appTable');
    const rows = table.querySelectorAll('tr.app-row');
    const headers = Array.from(table.querySelectorAll('th')).map(h => h.textContent.replace(/[▲▼]/g, '').trim());

    let csv = headers.join(',') + '\n';
    rows.forEach(row => {
        const cells = Array.from(row.cells).map(c => '"' + c.textContent.trim().replace(/"/g, '""') + '"');
        csv += cells.join(',') + '\n';
    });

    const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'Win32AppWorkload_Report.csv';
    link.click();
}

function toggleSection(sectionId) {
    const content = document.getElementById(sectionId);
    if (content) {
        content.style.display = content.style.display === 'none' ? '' : 'none';
    }
}

document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('searchBox').addEventListener('input', filterApps);
    document.getElementById('statusFilter').addEventListener('change', filterApps);
    document.getElementById('intentFilter').addEventListener('change', filterApps);
});
'@
}

function Generate-HtmlReport {
    param(
        [hashtable]$AppInventory,
        [string[]]$LogFileNames,
        [string]$LogDateRange,
        [PSCustomObject[]]$AllErrors,
        [PSCustomObject[]]$CheckinSessions,
        [PSCustomObject[]]$EspPhaseEvents
    )

    $apps = @($AppInventory.Values | Sort-Object Name)
    $totalApps = $apps.Count

    # Summary counts
    $installedCount = @($apps | Where-Object { $_.DetectionState -eq 'Detected' -and ($_.InstallResult -eq 'Success' -or $_.DetectionStatus -eq 'Success') }).Count
    $failedCount = @($apps | Where-Object { @($_.Errors).Count -gt 0 -or $_.InstallResult -eq 'Failed' -or $_.LatestEnforcementState -match 'Error' }).Count
    $pendingCount = @($apps | Where-Object { $_.LatestEnforcementState -match 'InProgress' }).Count
    $availableNotInstalled = @($apps | Where-Object { $_.IntentName -eq 'Available' -and $_.DetectionState -ne 'Detected' }).Count
    $lastEsp = if (@($EspPhaseEvents).Count -gt 0) { ($EspPhaseEvents | Select-Object -Last 1).Phase } else { 'N/A' }

    $css = Get-ReportCss
    $js = Get-ReportJavaScript

    $logFilesStr = ($LogFileNames | ForEach-Object { [System.Web.HttpUtility]::HtmlEncode($_) }) -join ', '
    $genTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

    # Build summary counts by intent and target type
    $requiredCount = @($apps | Where-Object { $_.IntentName -eq 'Required' }).Count
    $availableCount = @($apps | Where-Object { $_.IntentName -eq 'Available' }).Count
    $uninstallCount = @($apps | Where-Object { $_.IntentName -eq 'Uninstall' }).Count
    $userTargetCount = @($apps | Where-Object { $_.TargetTypeName -eq 'User' }).Count
    $deviceTargetCount = @($apps | Where-Object { $_.TargetTypeName -eq 'Device' }).Count

    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Win32 AppWorkload Log Analysis Report</title>
<style>
$css
</style>
</head>
<body>
<div class="container">

<!-- HEADER -->
<div class="report-header">
    <h1>Win32 AppWorkload Log Analysis Report</h1>
    <div class="subtitle">Microsoft Intune - Win32 App Deployment Analysis</div>
    <div class="meta">
        <span>&#128197; Generated: $genTime</span>
        <span>&#128196; Files: $logFilesStr</span>
        <span>&#128197; Log Range: $([System.Web.HttpUtility]::HtmlEncode($LogDateRange))</span>
    </div>
    <div class="meta">
        <span>Total Apps: $totalApps</span>
        <span>| Required: $requiredCount | Available: $availableCount | Uninstall: $uninstallCount</span>
        <span>| User-targeted: $userTargetCount | Device-targeted: $deviceTargetCount</span>
    </div>
</div>

<!-- DASHBOARD CARDS -->
<div class="dashboard">
    <div class="card info">
        <div class="card-value">$totalApps</div>
        <div class="card-label">Total Apps</div>
    </div>
    <div class="card success">
        <div class="card-value">$installedCount</div>
        <div class="card-label">Successfully Installed</div>
    </div>
    <div class="card error">
        <div class="card-value">$failedCount</div>
        <div class="card-label">Failed</div>
    </div>
    <div class="card warning">
        <div class="card-value">$pendingCount</div>
        <div class="card-label">Pending / In Progress</div>
    </div>
    <div class="card neutral">
        <div class="card-value">$availableNotInstalled</div>
        <div class="card-label">Available (Not Installed)</div>
    </div>
    <div class="card purple">
        <div class="card-value">$([System.Web.HttpUtility]::HtmlEncode($lastEsp))</div>
        <div class="card-label">ESP Phase</div>
    </div>
</div>

<!-- CONTROLS -->
<div class="controls">
    <input type="text" id="searchBox" placeholder="&#128269; Search apps by name..." />
    <select id="statusFilter">
        <option value="all">All Status</option>
        <option value="installed">Installed</option>
        <option value="failed">Failed</option>
        <option value="pending">Pending</option>
        <option value="available">Available</option>
        <option value="noactivity">No Activity</option>
    </select>
    <select id="intentFilter">
        <option value="all">All Intent</option>
        <option value="Required">Required</option>
        <option value="Available">Available</option>
        <option value="Uninstall">Uninstall</option>
    </select>
    <button onclick="toggleAllDetails()">Expand/Collapse All</button>
    <button class="btn-primary" onclick="exportCSV()">&#128229; Export CSV</button>
</div>

<!-- APP TABLE -->
<div class="section">
    <div class="section-header" onclick="toggleSection('appTableContent')">
        App Deployment Details
        <span class="toggle">Click to toggle</span>
    </div>
    <div id="appTableContent">
    <table class="app-table" id="appTable">
    <thead>
        <tr>
            <th onclick="sortTable(0)">Status<span class="sort-icon"></span></th>
            <th onclick="sortTable(1)">App Name<span class="sort-icon"></span></th>
            <th onclick="sortTable(2)">Intent<span class="sort-icon"></span></th>
            <th onclick="sortTable(3)">Target<span class="sort-icon"></span></th>
            <th onclick="sortTable(4)">Install Ctx<span class="sort-icon"></span></th>
            <th onclick="sortTable(5)">Detection<span class="sort-icon"></span></th>
            <th onclick="sortTable(6)">Install Result<span class="sort-icon"></span></th>
            <th onclick="sortTable(7)">Install Time<span class="sort-icon"></span></th>
            <th onclick="sortTable(8)">ESP Phase<span class="sort-icon"></span></th>
            <th onclick="sortTable(9)">Enforcement<span class="sort-icon"></span></th>
        </tr>
    </thead>
    <tbody>
"@

    foreach ($app in $apps) {
        # Determine status category
        $statusIcon = '&#10134;' # gray dash
        $statusCss = 'noactivity'
        if ($app.DetectionState -eq 'Detected' -and ($app.InstallResult -eq 'Success' -or $app.DetectionStatus -eq 'Success')) {
            $statusIcon = '&#9989;'  # green check
            $statusCss = 'installed'
        }
        elseif (@($app.Errors).Count -gt 0 -or $app.InstallResult -eq 'Failed' -or $app.LatestEnforcementState -match 'Error') {
            $statusIcon = '&#10060;'  # red X
            $statusCss = 'failed'
        }
        elseif ($app.LatestEnforcementState -match 'InProgress' -or $app.DownloadStatus -eq 'PendingDownload') {
            $statusIcon = '&#9203;'  # hourglass
            $statusCss = 'pending'
        }
        elseif ($app.IntentName -eq 'Available' -and $app.DetectionState -ne 'Detected') {
            $statusCss = 'available'
        }

        # Intent badge
        $intentBadge = switch ($app.IntentName) {
            'Required' { '<span class="badge badge-required">Required</span>' }
            'Available' { '<span class="badge badge-available">Available</span>' }
            'Uninstall' { '<span class="badge badge-uninstall">Uninstall</span>' }
            default { "<span class=`"badge`">$([System.Web.HttpUtility]::HtmlEncode($app.IntentName))</span>" }
        }

        # Target badge
        $targetBadge = switch ($app.TargetTypeName) {
            'User' { '<span class="badge badge-user">User</span>' }
            'Device' { '<span class="badge badge-device">Device</span>' }
            default { "<span class=`"badge`">$([System.Web.HttpUtility]::HtmlEncode($app.TargetTypeName))</span>" }
        }

        # Install context badge
        $ctxBadge = switch ($app.InstallContextName) {
            'System' { '<span class="badge badge-system">System</span>' }
            'User' { '<span class="badge badge-user">User</span>' }
            default { "<span class=`"badge`">$([System.Web.HttpUtility]::HtmlEncode($app.InstallContextName))</span>" }
        }

        # Detection state
        $detBadge = switch ($app.DetectionState) {
            'Detected' { '<span class="badge badge-detected">Detected</span>' }
            'NotDetected' { '<span class="badge badge-notdetected">Not Detected</span>' }
            default { '<span class="badge badge-noactivity">N/A</span>' }
        }

        # Install result
        $installResultDisplay = ''
        if ($app.InstallResult) {
            $resultBadgeClass = switch ($app.InstallResult) {
                'Success' { 'badge-success' }
                'Failed' { 'badge-failed' }
                default { 'badge-pending' }
            }
            $exitCodeStr = if ($app.InstallExitCode) { " ($($app.InstallExitCode))" } else { '' }
            $installResultDisplay = "<span class=`"badge $resultBadgeClass`">$([System.Web.HttpUtility]::HtmlEncode($app.InstallResult))$exitCodeStr</span>"
        }
        else {
            $installResultDisplay = '<span class="badge badge-noactivity">N/A</span>'
        }

        # Install time
        $installTimeStr = if ($app.InstallCompleteTime -and $app.InstallCompleteTime -ne [DateTime]::MinValue) {
            $app.InstallCompleteTime.ToString('yyyy-MM-dd HH:mm:ss')
        }
        else { '-' }

        # ESP Phase
        $espStr = if ($app.EspPhase) { [System.Web.HttpUtility]::HtmlEncode($app.EspPhase) } else { 'N/A' }

        # Enforcement state
        $enfStr = if ($app.LatestEnforcementState) {
            $enfClass = if ($app.LatestEnforcementState -match 'Success') { 'badge-success' }
                        elseif ($app.LatestEnforcementState -match 'Error') { 'badge-failed' }
                        elseif ($app.LatestEnforcementState -match 'InProgress') { 'badge-pending' }
                        else { 'badge-noactivity' }
            "<span class=`"badge $enfClass`">$([System.Web.HttpUtility]::HtmlEncode($app.LatestEnforcementState))</span>"
        }
        else { '<span class="badge badge-noactivity">N/A</span>' }

        $safeAppId = [System.Web.HttpUtility]::HtmlAttributeEncode($app.AppId)
        $safeName = [System.Web.HttpUtility]::HtmlEncode($app.Name)

        $html += @"
    <tr class="app-row" data-appid="$safeAppId" data-name="$safeName" data-status="$statusCss" data-intent="$($app.IntentName)" onclick="toggleDetail('$safeAppId')">
        <td class="status-icon">$statusIcon</td>
        <td><strong>$safeName</strong></td>
        <td>$intentBadge</td>
        <td>$targetBadge</td>
        <td>$ctxBadge</td>
        <td>$detBadge</td>
        <td>$installResultDisplay</td>
        <td>$installTimeStr</td>
        <td>$espStr</td>
        <td>$enfStr</td>
    </tr>
    <tr class="detail-row" id="detail-$safeAppId">
        <td colspan="10">
            <div class="detail-content">
"@

        # Detail - Commands
        $html += "            <h4>Install Command</h4>`n"
        $html += "            <div class=`"code-block`">$([System.Web.HttpUtility]::HtmlEncode($app.InstallCommandLine))</div>`n"
        $html += "            <h4>Uninstall Command</h4>`n"
        $html += "            <div class=`"code-block`">$([System.Web.HttpUtility]::HtmlEncode($app.UninstallCommandLine))</div>`n"

        # Detail - Detection Rules
        if ($app.DetectionRules -and @($app.DetectionRules).Count -gt 0) {
            $html += "            <h4>Detection Rules</h4>`n"
            $html += "            <ul class=`"detection-rules`">`n"
            foreach ($rule in $app.DetectionRules) {
                $html += "                <li>$([System.Web.HttpUtility]::HtmlEncode($rule))</li>`n"
            }
            $html += "            </ul>`n"
        }

        # Detail - Install Behavior
        if ($app.InstallBehavior) {
            $ib = $app.InstallBehavior
            $html += "            <h4>Install Behavior</h4>`n"
            $html += "            <div class=`"info-grid`">`n"
            $html += "                <div class=`"info-item`"><span class=`"label`">RunAs:</span><span class=`"value`">$([System.Web.HttpUtility]::HtmlEncode($ib.RunAs))</span></div>`n"
            $html += "                <div class=`"info-item`"><span class=`"label`">Max Retries:</span><span class=`"value`">$($ib.MaxRetries)</span></div>`n"
            $html += "                <div class=`"info-item`"><span class=`"label`">Max Runtime:</span><span class=`"value`">$($ib.MaxRunTimeInMinutes) min</span></div>`n"
            $html += "                <div class=`"info-item`"><span class=`"label`">Restart Behavior:</span><span class=`"value`">$($ib.DeviceRestartBehavior)</span></div>`n"
            $html += "                <div class=`"info-item`"><span class=`"label`">Requires Logon:</span><span class=`"value`">$($ib.RequiresLogon)</span></div>`n"
            $html += "            </div>`n"
        }

        # Detail - Return Codes
        if ($app.ReturnCodes -and @($app.ReturnCodes).Count -gt 0) {
            $html += "            <h4>Return Codes</h4>`n"
            $html += "            <table class=`"return-codes-table`"><tr><th>Code</th><th>Type</th></tr>`n"
            foreach ($rc in $app.ReturnCodes) {
                $html += "            <tr><td>$($rc.ReturnCode)</td><td>$([System.Web.HttpUtility]::HtmlEncode($rc.TypeName))</td></tr>`n"
            }
            $html += "            </table>`n"
        }

        # Detail - Dependencies
        if ($app.Dependencies) {
            $html += "            <h4>Dependencies</h4>`n"
            $html += "            <div class=`"code-block`">$([System.Web.HttpUtility]::HtmlEncode(($app.Dependencies | ConvertTo-Json -Compress)))</div>`n"
        }

        # Detail - Event Timeline (deduplicated: show first & last per event type, plus state changes)
        if ($app.EventTimeline -and @($app.EventTimeline).Count -gt 0) {
            $html += "            <h4>Event Timeline</h4>`n"
            $html += "            <ul class=`"timeline-list`">`n"

            # Group events by type, keep first/last and any with different Detail
            $sortedEvents = @($app.EventTimeline | Sort-Object Time)
            $grouped = @{}
            foreach ($evt in $sortedEvents) {
                $key = $evt.Event
                if (-not $grouped.ContainsKey($key)) { $grouped[$key] = [System.Collections.Generic.List[PSCustomObject]]::new() }
                $grouped[$key].Add($evt)
            }

            $filteredEvents = [System.Collections.Generic.List[PSCustomObject]]::new()
            foreach ($key in $grouped.Keys) {
                $evts = $grouped[$key]
                if ($evts.Count -le 2) {
                    # 1-2 events: keep all
                    foreach ($e in $evts) { $filteredEvents.Add($e) }
                }
                else {
                    # Keep first
                    $filteredEvents.Add($evts[0])
                    # Keep any middle events where Detail changed from previous
                    for ($ei = 1; $ei -lt $evts.Count - 1; $ei++) {
                        if ($evts[$ei].Detail -ne $evts[$ei - 1].Detail) {
                            $filteredEvents.Add($evts[$ei])
                        }
                    }
                    # Keep last (if different from the one just added)
                    $lastEvt = $evts[$evts.Count - 1]
                    $filteredEvents.Add($lastEvt)
                }
            }

            $filteredEvents = @($filteredEvents | Sort-Object Time)
            foreach ($evt in $filteredEvents) {
                $evtClass = switch ($evt.Type) {
                    3 { 'error-event' }
                    2 { 'warning-event' }
                    default { '' }
                }
                $timeStr = if ($evt.Time -and $evt.Time -ne [DateTime]::MinValue) { $evt.Time.ToString('HH:mm:ss.fff') } else { '??:??:??' }
                $dateStr = if ($evt.Time -and $evt.Time -ne [DateTime]::MinValue) { $evt.Time.ToString('yyyy-MM-dd') } else { '' }
                $html += "                <li class=`"$evtClass`"><span class=`"time`">$dateStr $timeStr</span><span class=`"event-type`">$([System.Web.HttpUtility]::HtmlEncode($evt.Event))</span> $([System.Web.HttpUtility]::HtmlEncode($evt.Detail))</li>`n"
            }
            $html += "            </ul>`n"
        }

        # Detail - Errors
        if ($app.Errors -and @($app.Errors).Count -gt 0) {
            $html += "            <h4>Error Details</h4>`n"
            foreach ($err in $app.Errors) {
                $errTimeStr = if ($err.Time) { $err.Time.ToString('yyyy-MM-dd HH:mm:ss') } else { '' }
                $html += "            <div style=`"color:var(--error);margin-bottom:4px;font-size:12px;`">[$errTimeStr] $([System.Web.HttpUtility]::HtmlEncode($err.Message))</div>`n"
            }
        }

        $html += @"
            </div>
        </td>
    </tr>
"@
    }

    $html += @"
    </tbody>
    </table>
    </div>
</div>
"@

    # ERROR SUMMARY SECTION (general errors only, deduplicated)
    if ($AllErrors -and @($AllErrors).Count -gt 0) {
        # Deduplicate: group by Message, keep first/last and any where Message changed
        $sortedErrors = @($AllErrors | Sort-Object Time)
        $groupedErrors = @{}
        foreach ($err in $sortedErrors) {
            $key = $err.Message
            if (-not $groupedErrors.ContainsKey($key)) { $groupedErrors[$key] = [System.Collections.Generic.List[PSCustomObject]]::new() }
            $groupedErrors[$key].Add($err)
        }
        $filteredErrors = [System.Collections.Generic.List[PSCustomObject]]::new()
        foreach ($key in $groupedErrors.Keys) {
            $errs = $groupedErrors[$key]
            if ($errs.Count -le 2) {
                foreach ($e in $errs) { $filteredErrors.Add($e) }
            }
            else {
                $filteredErrors.Add($errs[0])
                $filteredErrors.Add($errs[$errs.Count - 1])
            }
        }
        $filteredErrors = @($filteredErrors | Sort-Object Time)

        $html += @"

<!-- ERROR SUMMARY -->
<div class="section">
    <div class="section-header" onclick="toggleSection('errorSummaryContent')">
        Error Summary ($($filteredErrors.Count) unique errors from $(@($AllErrors).Count) total)
        <span class="toggle">Click to toggle</span>
    </div>
    <div id="errorSummaryContent">
    <table class="error-summary-table">
    <thead>
        <tr><th>Time</th><th>Message</th></tr>
    </thead>
    <tbody>
"@
        foreach ($err in $filteredErrors) {
            $errTime = if ($err.Time) { $err.Time.ToString('yyyy-MM-dd HH:mm:ss') } else { '' }
            $html += "    <tr><td style=`"white-space:nowrap`">$errTime</td><td class=`"error-msg`">$([System.Web.HttpUtility]::HtmlEncode($err.Message))</td></tr>`n"
        }

        $html += @"
    </tbody>
    </table>
    </div>
</div>
"@
    }

    # CHECKIN SESSIONS

    if ($CheckinSessions -and @($CheckinSessions).Count -gt 0) {
        $html += @"
<div class="section">
    <div class="section-header" onclick="toggleSection('checkinContent')">
        Check-in Sessions ($(@($CheckinSessions).Count) sessions detected)
        <span class="toggle">Click to toggle</span>
    </div>
    <div id="checkinContent" style="display:none">
    <table class="error-summary-table">
    <thead>
        <tr><th>#</th><th>Start Time</th><th>Active User Sessions</th></tr>
    </thead>
    <tbody>
"@
        $i = 1
        foreach ($session in $CheckinSessions) {
            $sessionTime = if ($session.StartTime) { $session.StartTime.ToString('yyyy-MM-dd HH:mm:ss') } else { '' }
            $html += "    <tr><td>$i</td><td>$sessionTime</td><td>$($session.UserSessions)</td></tr>`n"
            $i++
        }
        $html += @"
    </tbody>
    </table>
    </div>
</div>
"@
    }

    # Footer
    $html += @"

<div style="text-align:center;padding:24px;color:var(--text-secondary);font-size:12px;">
    Win32 AppWorkload Log Analyzer | Generated by PowerShell | $(Get-Date -Format 'yyyy')
</div>

</div> <!-- /container -->

<script>
$js
</script>
</body>
</html>
"@

    return $html
}

# ============================================================
# Section 6: Main Execution
# ============================================================

# Add System.Web for HtmlEncode
Add-Type -AssemblyName System.Web -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Win32 AppWorkload Log Analyzer" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# --- Step 1: Discover log files ---
$filesToProcess = @()

if ($LogFiles) {
    foreach ($f in $LogFiles) {
        if (Test-Path $f) {
            $filesToProcess += (Resolve-Path $f).Path
        }
        else {
            Write-Warning "File not found: $f"
        }
    }
}
elseif ($LogFolder) {
    if (Test-Path $LogFolder) {
        $discovered = @(Get-ChildItem -Path $LogFolder -File | Where-Object { $_.Name -match 'AppWorkload.*\.log$' } | Select-Object -ExpandProperty FullName)
        if ($discovered.Count -gt 0) {
            $filesToProcess = $discovered
            Write-Host "Discovered $($filesToProcess.Count) log file(s) in folder." -ForegroundColor Green
        }
        else {
            Write-Error "No AppWorkload*.log files found in: $LogFolder"
            return
        }
    }
    else {
        Write-Error "Folder not found: $LogFolder"
        return
    }
}
else {
    # Default: try local IME log folder
    $defaultPath = "$env:ProgramData\Microsoft\IntuneManagementExtension\Logs"
    if (Test-Path $defaultPath) {
        $discovered = @(Get-ChildItem -Path $defaultPath -File | Where-Object { $_.Name -match 'AppWorkload.*\.log$' } | Select-Object -ExpandProperty FullName)
        if ($discovered.Count -gt 0) {
            $filesToProcess = $discovered
            Write-Host "Auto-discovered $($filesToProcess.Count) log file(s) from default IME path." -ForegroundColor Green
        }
    }

    if ($filesToProcess.Count -eq 0) {
        Write-Host ""
        Write-Host "Usage:" -ForegroundColor Yellow
        Write-Host "  .\Analyze-Win32AppWorkload.ps1 -LogFolder <path>"
        Write-Host "  .\Analyze-Win32AppWorkload.ps1 -LogFiles <file1>,<file2>"
        Write-Host "  .\Analyze-Win32AppWorkload.ps1 -LogFolder <path> -ShowInBrowser"
        Write-Host ""
        Write-Host "Or run on an Intune-managed device to auto-discover logs from:"
        Write-Host "  $defaultPath" -ForegroundColor Cyan
        return
    }
}

if ($filesToProcess.Count -eq 0) {
    Write-Error "No valid log files to process."
    return
}

Write-Host ""
Write-Host "[Step 1/5] Merging $($filesToProcess.Count) log file(s)..." -ForegroundColor Yellow
$logFileNames = $filesToProcess | ForEach-Object { Split-Path $_ -Leaf }

# --- Step 2: Merge and Parse ---
$rawLines = Merge-LogFiles -FilePaths $filesToProcess
Write-Host "  Total lines: $($rawLines.Count)" -ForegroundColor Gray

Write-Host "[Step 2/5] Parsing log entries..." -ForegroundColor Yellow
$logEntries = @(Parse-CMTraceLog -LogContent $rawLines)
Write-Host "  Parsed entries: $($logEntries.Count)" -ForegroundColor Gray

if ($logEntries.Count -eq 0) {
    Write-Error "No valid log entries parsed. Check if the files are in CMTrace format."
    return
}

# Date range
$sortedEntries = $logEntries | Where-Object { $_.DateTime -ne [DateTime]::MinValue } | Sort-Object DateTime
$dateRange = ""
if ($sortedEntries.Count -gt 0) {
    $firstDate = ($sortedEntries | Select-Object -First 1).DateTime.ToString('yyyy-MM-dd HH:mm:ss')
    $lastDate = ($sortedEntries | Select-Object -Last 1).DateTime.ToString('yyyy-MM-dd HH:mm:ss')
    $dateRange = "$firstDate  ~  $lastDate"
    Write-Host "  Date range: $dateRange" -ForegroundColor Gray
}

# --- Step 3: Extract App Inventory ---
Write-Host "[Step 3/5] Extracting app inventory from policies..." -ForegroundColor Yellow
$appInventory = Parse-PolicyJSON -LogEntries $logEntries

if ($appInventory.Count -eq 0) {
    Write-Error "No apps found in 'Get policies' JSON. The log may not contain policy data."
    return
}

Write-Host "  Found $($appInventory.Count) app(s) in policy." -ForegroundColor Gray

# --- Step 4: Extract per-app events ---
Write-Host "[Step 4/5] Extracting per-app events and states..." -ForegroundColor Yellow
$espEvents = @(Get-EspPhaseEvents -LogEntries $logEntries)
$checkinSessions = @(Get-CheckinSessions -LogEntries $logEntries)
Get-AppEvents -LogEntries $logEntries -AppInventory $appInventory -EspPhaseEvents $espEvents

$allErrors = @(Get-AllErrors -LogEntries $logEntries -AppInventory $appInventory)

# Summary
$detected = @($appInventory.Values | Where-Object { $_.DetectionState -eq 'Detected' }).Count
$notDetected = @($appInventory.Values | Where-Object { $_.DetectionState -eq 'NotDetected' }).Count
$noActivity = @($appInventory.Values | Where-Object { -not $_.DetectionState }).Count
Write-Host "  Detected: $detected | Not detected: $notDetected | No activity: $noActivity" -ForegroundColor Gray
$allErrors = @($allErrors)
Write-Host "  Errors found: $($allErrors.Count)" -ForegroundColor $(if ($allErrors.Count -gt 0) { 'Red' } else { 'Gray' })

# --- Step 5: Generate HTML Report ---
Write-Host "[Step 5/5] Generating HTML report..." -ForegroundColor Yellow

$htmlContent = Generate-HtmlReport -AppInventory $appInventory -LogFileNames $logFileNames -LogDateRange $dateRange -AllErrors $allErrors -CheckinSessions $checkinSessions -EspPhaseEvents $espEvents

# Determine output path
if (-not $OutputPath) {
    $firstFileDir = Split-Path $filesToProcess[0] -Parent
    $OutputPath = Join-Path $firstFileDir "Win32AppWorkload_Report.html"
}

# Handle directory in OutputPath
if (Test-Path $OutputPath -PathType Container) {
    $OutputPath = Join-Path $OutputPath "Win32AppWorkload_Report.html"
}

# Ensure output directory exists
$outputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$htmlContent | Out-File -FilePath $OutputPath -Encoding UTF8 -Force
Write-Host ""
Write-Host "Report generated successfully!" -ForegroundColor Green
Write-Host "  Output: $OutputPath" -ForegroundColor Cyan
Write-Host ""

if ($ShowInBrowser) {
    Write-Host "Opening in browser..." -ForegroundColor Gray
    Start-Process $OutputPath
}
